### ISSUE TITLE
Cannot find module 'underscore'

### ISSUE THREAD

**Issue by ralphievolt** [orionsoft/react-meteor-data#4]
I added `underscore` already using `meteor add underscore ` but i kept seeing this error in my web console

![screen shot 2016-12-19 at 11 20 26 am](https://cloud.githubusercontent.com/assets/5282658/21300259/6e3b120e-c5dd-11e6-8f51-e41a1ce685a3.png)

**Comment by nicolaslopezj** [comment]
```v0.1.4``` should fix this

**Comment by Timonzimm** [comment]
I still have the issue (`v0.1.4` installed), even when I add underscore with `meteor add underscore` manually.

**Comment by nicolaslopezj** [comment]
Try putting ```underscore``` before ```react-meteor-data``` in ```.meteor/packages```

**Comment by Timonzimm** [comment]
Issue still present. Changing the order in `.meteor/packages` doesn't remove the error.

**Comment by nicolaslopezj** [comment]
And version 0.1.5?

**Comment by Timonzimm** [comment]
Now it's better! Thank you!
